name: Automated Nerdpack Publication
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type YES to confirm publishing the nerdpack"
        required: true

jobs:
  publish-nerdpack:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: [self-hosted, ecs]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20.x" }

      - name: Install Node Modules
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Lint
        run: |
          git pull origin main
          git add .
          git commit -m "Automated updates"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ github.head_ref }}
