name: Automated Nerdpack Publication
on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'test')) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20.x" }

      - name: Install Node Modules
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Commit and Push Lint
        run: |
          git commit -m "Update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
