name: Automated Nerdpack Publication
on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'test')) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20.x" }

      - name: Install Node Modules
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Lint
        run: |
          git add .
          git commit -m "Automated updates"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -u origin ${GITHUB_REF##*/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
