name: Automated Nerdpack Publication
on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.labels.*.name, 'test')) }}

    steps:
      - run: echo "Hello from GA"
