name: Automated Nerdpack Publication
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: read

jobs:
  publish:
    if: >
      github.event.review.state == 'approved' &&
      contains(github.event.review.body, '/publish')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20.x" }

      - name: Install Node Modules
        uses: bahmutov/npm-install@v1

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge with main
        run: |
          git config pull.rebase false
          git pull origin main

      - name: Lint
        run: npm run lint

      - name: Commit and Push Lint
        run: |
          git add .
          git commit -m "Automated updates"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin "${HEAD_REF}"
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
